apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: redis-bak-svc-acct
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role 
  name: pod-reader 
  apiGroup: rbac.authorization.k8s.io