apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timescaledb.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "timescaledb.fullname" . }}-credentials
    helm.sh/chart: {{ include "postgresql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  PATRONI_SUPERUSER_PASSWORD: {{ .Values.patroni.superuserPassword | b64enc | quote }}
  PATRONI_REPLICATION_PASSWORD: {{ .Values.patroni.replicationPassword | b64enc | quote }}
  PATRONI_admin_PASSWORD: {{ .Values.patroni.adminPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timescaledb.fullname" . }}-pgbackrest
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "timescaledb.fullname" . }}-pgbackrest
    helm.sh/chart: {{ include "postgresql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  PGBACKREST_REPO1_S3_BUCKET: {{ .Values.backups.bucket | b64enc | quote }}
  PGBACKREST_REPO1_PATH: {{ .Values.backups.path | b64enc | quote }}
  PGBACKREST_REPO1_S3_REGION: {{ .Values.backups.aws.region | b64enc | quote }}
  PGBACKREST_REPO1_S3_KEY: {{ .Values.backups.aws.accessKey | b64enc | quote }}
  PGBACKREST_REPO1_S3_KEY_SECRET: {{ .Values.backups.aws.secretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "timescaledb.fullname" . }}-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "timescaledb.fullname" . }}-certificate
    helm.sh/chart: {{ include "postgresql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "postgresql.gen-certs" . ) | indent 2 }}
