
apiVersion: v1
kind: Service
metadata:
  name: {{ default .Release.Name .Values.timescaledb.clusterName | trunc 63 -}}-headless
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ default .Release.Name .Values.timescaledb.clusterName | trunc 63 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
{{- if .Values.timescaledb.pgBouncer.enabled }}
  - name: pgbouncer
    port: {{ .Values.timescaledb.pgBouncer.port }}
    targetPort: pgbouncer
    protocol: TCP
{{- end }}
  - name: postgresql
    # This always defaults to 5432, even if `!loadBalancer.enabled`.
    port: {{ .Values.timescaledb.loadBalancer.port }}
    targetPort: postgresql
    protocol: TCP
  selector:
    app: {{ template "timescaledb.fullname" . }}
    cluster-name: {{ default .Release.Name .Values.timescaledb.clusterName | trunc 63 }}
