{{- if .Values.elasticsearch.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-es-http
  namespace: {{ .Values.elasticsearch.ingress.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: elasticsearch-es-http
    helm.sh/chart: {{ include "elastic-cloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.elasticsearch.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.elasticsearch.ingress.tls }}
  tls:
  {{- range .Values.elasticsearch.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.elasticsearch.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: elasticsearch-es-http
              servicePort: 9200
        {{- end }}
  {{- end }}
{{- end }}
