{{- if .Values.backups.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-snapshotter
  namespace: {{ .Values.backups.namespace | default .Release.Namespace }}
spec:
  schedule: {{ .Values.backups.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: snapshotter
            image: centos:7
            volumeMounts:
              - name: es-basic-auth
                mountPath: /mnt/elastic/es-basic-auth
            command:
            - /bin/bash
            args:
            - -c
            - 'curl -s -i -k -u "elastic:$(</mnt/elastic/es-basic-auth/elastic)" -XPUT "https://elasticsearch-es-http:9200/_snapshot/{{ .Values.backups.repositoryName }}/%3Csnapshot-%7Bnow%2Fd%7D%3E" | tee /dev/stderr | grep "200 OK"'
          restartPolicy: OnFailure
          volumes:
          - name: es-basic-auth
            secret:
              secretName: elasticsearch-es-elastic-user
{{- end }}