{{- if .Values.kibana.enabled -}}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elasticsearch
  namespace: {{ .Values.kibana.namespace | default .Release.Namespace }}
spec:
{{ toYaml .Values.kibana.spec | indent 2 }}
{{- end }}
