apiVersion: v1
kind: Secret
metadata:
  name: elastic-cloud-aws-credentials
  namespace: {{ .Values.backups.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "elastic-cloud.fullname" . }}-aws
    helm.sh/chart: {{ include "elastic-cloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.backups.enabled }}
  accessKey: {{ .Values.backups.aws.accessKey | b64enc | quote }}
  secretKey: {{ .Values.backups.aws.secretKey | b64enc | quote }}
{{- end }}