backups:
  enabled: false
  schedule: "* * * * *"
  aws:
    accessKey:
    secretKey:
    location: mybucket/path/to/backups
  image:
    repository: maorfr/skbn
    tag: 0.5.0
    pullPolicy: IfNotPresent

redis: {}
